export const VOCABULARY = {
  shell: {
    title: "InstaSorter",
    subtitle: "Instagram Archivist & Sorter",
    navDashboard: "Dashboard",
    navImport: "Import Media",
    navAnalytics: "Analytics",
    navSettings: "Settings",
    footerText: "InstaSorter - Client-side IndexedDB Media Archivist",
    mobileTitle: "Instasorter",
    mediaOrganizer: "Media Organizer",
    smartCollections: "Collections",
  },
  dashboard: {
    title: "Instagram Library",
    subtitle:
      "Manage, filter, sort, and organize your saved Instagram posts and reels.",
    searchPlaceholder: "Search (e.g. creator:john post:hello)...",
    sortFilterTitle: "Sort & Filter Library",
    sortOptions: "Sort Options",
    sortDirection: "Sort Direction",
    sortBySavedAt: "Date Saved",
    sortByLikes: "Engagement (Comments)",
    sortByCreator: "Creator Username",
    filterTitle: "Filter Categories",
    filterFavorites: "Starred Favorites Only",
    filterArchived: "Show Archived Items",
    filterReadLater: "Marked Read Later",
    filterTypeAll: "All Media Types",
    filterTypeImage: "Images Only",
    filterTypeVideo: "Videos & Reels Only",
    filterTypeCarousel: "Carousels Only",
    layoutGrid: "Grid Layout",
    layoutList: "List Layout",
    noPostsTitle: "No Bookmarks cataloged yet",
    noPostsSubtitle:
      "Go to the Import tab to drag-and-drop your Instagram data archive.",
    importSampleBtn: "Or Seed Sample Data",
    selectionLabel: "selected",
    clearSelection: "Deselect",
    batchFavorite: "Star Selected",
    batchArchive: "Archive Selected",
    batchDelete: "Delete Selected",
    collectionsSection: "Collections & Folders",
    newCollectionPlaceholder: "Create new collection...",
    smartRulesSection: "Smart Rules Auto-Sorter",
    smartRulesDesc:
      "Define keyword or username auto-routing rules to categorize posts dynamically.",
    addRule: "Add Rule",
    itemsSelected: "Items Selected",
    addCollection: "Add",
    removeCollection: "Remove",
    archive: "Archive",
    unarchive: "Activate",
    rescrape: "Re-scrape",
    delete: "Delete",
    collectionPlaceholder: "Collection Name",
    noPostsFound: "No Posts Found",
    adjustFilters:
      "Adjust your filters or search query to see your library items.",
    showingPosts: "Showing {current} of {total} posts.",
    loadMore: "(Click or scroll down to load more)",
    scrollTop: "Scroll back to top",
  },
  import: {
    title: "Import Instagram Data",
    subtitle:
      "Load your downloaded Instagram bookmarks and saved posts metadata offline.",
    dragDropTitle: "Drag & drop your Instagram data files here",
    dragDropDesc:
      "Supports raw JSON (saved_posts.json) or full ZIP exports downloaded from Meta.",
    selectFileBtn: "Select File manually",
    loadingText: "Parsing files and indexing data...",
    successText: "Successfully imported metadata and queued image downloading!",
    failedText: "Invalid Instagram export structure. Please check file format.",
    scrapeStatusTitle: "Background Thumbnail Downloader",
    scrapeStatusDesc:
      "Active Background Downloader retrieves real-time preview thumbnails securely.",
    scrapeCompleted: "Completed",
    scrapeActive: "Active worker downloading previews...",
    importArchive: "Import Instagram Archive",
    importArchiveDesc:
      "Upload your exported Instagram JSON or ZIP data to index, tag, and sort your saved posts locally.",
    dropHere: "Drop your archive here!",
    dragDrop: "Drag & drop your file",
    fileFormats:
      "Supports Instagram .json files, or .zip archives exported directly from Meta.",
    selectDeviceFile: "Select File from Device",
    readingDataset: "Reading and compiling Instagram dataset...",
    processingPosts: "Processing posts: {current} of {total} ({percent}%)",
    completedSuccessfully: "Import completed successfully",
    failedTitle: "Import failed",
    howToExportTitle: "How to export your Instagram data",
    step1: "Log into Instagram on your mobile device or web browser.",
    step2:
      "Navigate to your profile, tap the menu button, and open Accounts Center.",
    step3:
      "Select Your information and permissions then click Download your information.",
    step4:
      'Request a download, select "Saved items", select your desired date range, and choose JSON format.',
    step5:
      "Once Meta notifies you that the export is ready (typically takes a few minutes to hours), download the file and drag it here!",
  },
  analytics: {
    title: "Library Intelligence",
    subtitle:
      "In-depth insights, timeline trends, media mix distribution, and taxonomy diagnostics.",
    totalPosts: "Total Cataloged Posts",
    favoriteRatio: "Favorite/Starred Ratio",
    archiveRatio: "Archived Volume",
    uniqueCollections: "Unique Folders",
    uniqueTags: "Unique Taxonomy Tags",
    timeTrendTitle: "Saved Activity Trend",
    timeTrendDesc:
      "Chronological frequency of Instagram posts archived over time.",
    mediaMixTitle: "Media Composition Matrix",
    mediaMixDesc:
      "Breakdown of file types: Images, Videos, Reels, and Carousel slides.",
    topTagsTitle: "Popular Taxonomies",
    topTagsDesc:
      "The most recurring metadata hashtags and tags across your library.",
    engagementTitle: "Engagement & Comments Distribution",
    engagementDesc: "Average comments count categorized by media composition.",
  },
  settings: {
    title: "Settings",
    subtitle:
      "Customize your archivist identity, manage database size, and initiate system backups.",
    profileSectionTitle: "Profile Settings",
    appearanceSectionTitle: "Appearance & Interface",
    themeLabel: "Visual Theme",
    themeDesc:
      "Switch between the Crisp Studio light theme and the Dark Room dark theme.",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    animationsLabel: "Interface Animations",
    animationsDesc:
      "Enable or disable reduced motion for interface transitions.",
    compactModeLabel: "Compact List View",
    compactModeDesc: "Reduce padding and margins in the grouped list view.",
    displayNameLabel: "Archivist Display Name",
    usernameLabel: "Instagram Username",
    emailLabel: "Email Address",
    roleLabel: "Arhivist Role",
    saveProfileBtn: "Save Profile",
    editProfileBtn: "Edit Profile Details",
    dbAdminTitle: "Database Administration & Maintenance",
    dbAdminDesc:
      "Execute low-level storage routines, manage local cache, and perform full system backups.",
    backupTitle: "Download Complete Storage Backup",
    backupDesc:
      "Export a serialized JSON archive containing all categorized posts, custom notes, smart rules, and database tags.",
    backupBtn: "Backup Library",
    cleanCacheTitle: "Clean & Retry Thumbnail Cache",
    cleanCacheDesc:
      "Scans database records, resets failed thumbnail download statuses, and runs background worker.",
    cleanCacheBtn: "Clean Cache",
    seedTitle: "Seed Mock Presentation Dataset",
    seedDesc:
      "Reset IndexedDB and populate it with pre-configured sample posts with multiple tags and collections.",
    seedBtn: "Load Sample Data",
    purgeTitle: "Purge Local Library Storage",
    purgeDesc:
      "Irreversibly wipe all bookmarks, collections, customized notes, and stored data from Dexie IndexedDB.",
    purgeBtn: "Clear Database",
  },
  grouped: {
    title: "Collections",
    subtitle: "",
    allGroups: "All Groups",
    collections: "Collections",
    creators: "Creators",
    searchPlaceholder: "Search groups...",
    searchInGroup: "Search in group...",
    sortLabel: "Sort:",
    sortMostItems: "Most Items",
    sortFewestItems: "Fewest Items",
    sortAZ: "A-Z",
    sortZA: "Z-A",
    noCollectionsTitle: "No Collections Found",
    noCollectionsDesc:
      "No collections match your search criteria or your collections are empty.",
    noCreatorsTitle: "No Creators Found",
    noCreatorsDesc:
      "No creators match your search criteria or no posts found with creator information.",
    backToGroups: "Back to groups",
    collectionLabel: "Collection",
    creatorLabel: "Creator",
    itemsLabel: "items",
    itemLabel: "item",
    allMedia: "All Media",
    images: "Images",
    videos: "Videos",
    carousels: "Carousels",
    sortSavedNewest: "Saved: Newest",
    sortSavedOldest: "Saved: Oldest",
    sortCaptionAZ: "Caption A-Z",
    sortCaptionZA: "Caption Z-A",
    noPostsTitle: "No Posts Found",
    noPostsDesc: "No posts match your search or filter selection.",
    closePreview: "Close Preview",
  },
  shortcuts: {
    title: "Keyboard Shortcuts",
    subtitle: "Power-user keyboard shortcuts",
    globalNav: "Global Navigation",
    navHome: "Navigate to Home",
    navAnalytics: "Navigate to Analytics",
    navGrouped: "Navigate to Grouped / Folders",
    navImport: "Navigate to Import Data",
    navSettings: "Navigate to Settings",
    toggleGuide: "Toggle Shortcut Guide",
    mainView: "Main View (Post Grid & List)",
    navFocus: "Navigate Focus between Posts",
    openDetails: "Open Highlighted Post Details",
    toggleStar: "Toggle Star / Favorite",
    toggleArchive: "Toggle Archive",
    toggleReadLater: "Toggle Read Later",
    copyLink: "Copy Original Link",
    detailSheet: "Active Post Detail Sheet",
    nextPrev: "Next / Previous Saved Post",
    closeDetail: "Close Detail View",
    gotIt: "Got It",
  },
  modal: {
    addTitle: "Add Custom Bookmark",
    addSubtitle: "Manually log a post or reel with metadata.",
    urlLabel: "Instagram Post URL",
    urlPlaceholder: "https://www.instagram.com/p/...",
    creatorLabel: "Creator Username",
    creatorPlaceholder: "username",
    captionLabel: "Caption / Description",
    captionPlaceholder: "Write a captivating description...",
    typeLabel: "Media Type",
    coverLabel: "Preview Cover Image",
    coverPlaceholder: "https://unsplash.com/... or choose random below",
    notesLabel: "Custom Curator Notes",
    notesPlaceholder: "Add context, tags, ideas, or reminders...",
    tagsLabel: "Taxonomy Tags",
    tagsPlaceholder: "Press enter to add tag",
    collectionsLabel: "Collections / Folders",
    collectionsPlaceholder: "Press enter to add to collection",
    cancelBtn: "Cancel",
    submitBtn: "Add to Library",
  },
  postcard: {
    addToCollection: "Add to Collection",
    newCollection: "New collection...",
    add: "Add",
    scrapeFailed: "Scrape Failed",
    openPost: "Open Post",
    retry: "Retry",
    noCaption: "No caption provided",
    you: "You",
    loadingThumbnail: "Loading thumbnail...",
    more: "more",
    personalNote: "Personal Curation Note",
    saving: "Saving...",
    saved: "Saved",
    notePlaceholder: "Add annotations, curation insights, or context notes...",
    instagramComments: "Instagram Comments",
    noCommentsYet: "No comments yet. Write one below!",
    commentPlaceholder: "Add a comment on this post...",
    tagPlaceholder: "tag...",
    likedAdded: "Added to Favorites",
    likedRemoved: "Removed from Favorites",
    bookmarkAdded: "Saved to Bookmarks",
    bookmarkRemoved: "Removed from Bookmarks",
    archivedAdded: "Post Archived",
    archivedRemoved: "Post Unarchived",
    tagAdded: "Added tag #{tag}",
    tagRemoved: "Removed tag #{tag}",
    collectionAdded: 'Added to Collection "{collection}"',
    collectionRemoved: 'Removed from Collection "{collection}"',
    commentPosted: "Comment posted!",
    commentDeleted: "Comment deleted",
    linkCopied: "Link copied to clipboard!",
  },
};
